### ISSUE TITLE
OS X Homebrew Formula

### ISSUE THREAD

**Issue by olleolleolle** [npryce/adr-tools#1]
Something like this installs it

```ruby
class AdrTools < Formula
  desc "A command-line tool for working with Architecture Decision Records (ADRs)."
  homepage "https://github.com/npryce/adr-tools"
  url "https://codeload.github.com/npryce/adr-tools/tar.gz/1.0.0"
  sha256 "ceeba995d2319ba2735dd3c613bf145070efb8984886887a9edde7d498354b4b"

  def install
    bin.install Dir["src/*"] - Dir["src/*.md"]
  end

  test do
    system "true"
  end
end
```

**Comment by npryce** [comment]
Cool.  I must admit, I don't know what to do with this.  I'd like packaging and distribution via third party repositories (homebrew, deb, rpm, etc.) to be managed outside this project because there are so many different options.

**Comment by olleolleolle** [comment]
Indeed, all I'd want is a version tag in your repository, so that I can make a package request like this to the Homebrew upstream repo.

**Comment by npryce** [comment]
Great!  Thanks.  I've tagged the repo' with `1.0.0`.

**Comment by olleolleolle** [comment]
I'll be darned:

```shell
> $ brew audit --strict --online adr-tools
==> brew style adr-tools

1 file inspected, no offenses detected

==> audit problems
adr-tools:
 * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
 * GitHub repository too new (<30 days old)

Error: 2 problems in 1 formula
```

**Comment by npryce** [comment]
Would a "tap" work?

http://octavore.com/posts/2016/02/15/distributing-go-apps-os-x

**Comment by olleolleolle** [comment]
A "tap" _would_ work!

**Comment by olleolleolle** [comment]
Would you be OK with me setting that up, or do you want to control this package yourself? (If I set it up, I could add you as "owner" should you wish to.)

**Comment by npryce** [comment]
Go ahead and set it up and I'll link to it from the README of this repo.  I'm happy to be an owner or committer, but probably won't make a lot of commits.

**Comment by olleolleolle** [comment]
Current status: I'm clumsy. But at least I'm clumsy using package management.

```
> $ adr new haha
cat: /usr/local/bin/template.md: No such file or directory
doc/adr/0001-haha.md
```

I'll just have to figure out a way for the thing to find its template.md and other file somehow.

**Comment by olleolleolle** [comment]
To try/fork/tweak:

https://github.com/olleolleolle/homebrew-adr-tools

```
brew install olleolleolle/adr-tools/adr_tools
```

**Comment by olleolleolle** [comment]
Ah, uninstall that thing, and then `brew update` to fetch it again.

There are now two `inreplace` calls that made the difference:

https://github.com/olleolleolle/homebrew-adr-tools/blob/master/adr_tools.rb

**Comment by npryce** [comment]
I've created a new issue #2 about making it easier to configure an installation with different data and binary directories.

**Comment by npryce** [comment]
I'll close this and we can open another issue when the project is considered mature enough to be a proper brew package

**Comment by olleolleolle** [comment]
_Usage!_

**Comment by npryce** [comment]
I've added instructions for Homebrew users to the adr-tools README.
