### ISSUE TITLE
Use ISO 8601 Date Format

### ISSUE THREAD

**Issue by alexbestul** [npryce/adr-tools#14]
I found this repository via a link from the latest [ThoughtWorks tech radar](https://www.thoughtworks.com/radar/techniques).  Congrats on the publicity--I hope you enjoy some internet popularity because of it.

I was a little confused by the format of dates in the generated markdown files.  Being in the United States, I'm used to seeing mm/dd/yyyy instead of dd/mm/yyyy.  When I first read [0001-record-architecture-decisions.md](https://github.com/npryce/adr-tools/blob/147b54a2d527a834e0aefc1dfd17f04606d63d4a/doc/adr/0001-record-architecture-decisions.md), I thought the file was dated in the future.

Since ADR is a communication tool, it should be as unambiguous as possible.  With that goal in mind, I think it makes sense to follow the ISO 8601 recommendations for date formatting--yyyy-mm-dd.

I see that it's possible to override the default date format via config.sh, but I still think it makes sense for the tool's default to be the ISO standard--it would make the tool friendlier to adopt, and save new users some head-scratching.

**Comment by npryce** [comment]
I agree.  ISO 8601 is the right format to use.
