### ISSUE TITLE
Deprecated flag used with "find" command

### ISSUE THREAD

**Issue by StefanSmith** [npryce/adr-tools#21]
After installing adr to `/opt/adr-tools/1.2.0/` on Ubuntu 16.04 and running `adr`, the following error is shown:

```
usage: /opt/adr-tools/1.2.0/adr-help COMMAND [ARG] ...
COMMAND is one of: 
find: invalid mode ‘+111’
Run 'adr help COMMAND' for help on a specific command.
```

After running `sudo sed -i  's@-perm +111@-perm /111@' /opt/adr-tools/1.2.0/*`, running `adr` produces:

```
usage: /opt/adr-tools/1.2.0/adr-help COMMAND [ARG] ...
COMMAND is one of: 
  init
  new
  generate
  help
  list
Run 'adr help COMMAND' for help on a specific command.
```

http://man7.org/linux/man-pages/man1/find.1.html sayeth:

```
The syntax -perm +MODE was removed in findutils-4.5.12, in favour of
       -perm /MODE.  The +MODE syntax had been deprecated since
       findutils-4.2.21 which was released in 2005.
```

On my system, `find --version` gives `find (GNU findutils) 4.7.0-git`

**Comment by npryce** [comment]
The `/111` syntax is not supported by MacOS X (at least, not in El Capitan).  And I don't know about other BSD variants.

I'll need an alternative implementation that works on Mac and Linux.

**Comment by StefanSmith** [comment]
Two other options: (1) make the code take alternative code paths for
different platforms/find versions or (2) fall back to /111 when +111
doesn't work. Yuck.

On 12 Feb 2017 11:01 am, "Nat Pryce" <notifications@github.com> wrote:

The /111 syntax is not supported by MacOS X (at least, not in El Capitan).
And I don't know about other BSD variants.

I'll need an alternative implementation that works on Mac and Linux.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/npryce/adr-tools/issues/21#issuecomment-279210763>, or mute
the thread

**Comment by npryce** [comment]
I've pushed a fix that uses a for loop and `if [ -x ...` instead of `find ... -perm ...`
