### ISSUE TITLE
Brew command on INSTALL.md does not work

### ISSUE THREAD

**Issue by gigaSproule** [npryce/adr-tools#24]
On the [INSTALL.md](https://github.com/npryce/adr-tools/blob/master/INSTALL.md), it states that this can be installed with `brew install olleolleolle/adr-tools/adr_tools`, but this throws the error:
```
Error: inreplace failed
src/adr-init:
  expected replacement of "/usr/local/Cellar/adr_tools/2.0.0/config.sh" with "/usr/local/Cellar/adr_tools/2.0.0/bin/config.sh"
```

I'm guessing this is due to `config.sh` being removed in `2.0.0`. It might be worth removing the brew command, or linking to a working variant? I think there is a working tap by @olleolleolle https://github.com/olleolleolle/homebrew-adr-tools. I've not tried it though, so maybe it doesn't.

**Comment by olleolleolle** [comment]
@gigaSproule YES, it got broke.
