### ISSUE TITLE
Suggestion: adr-config could report absolute path

### ISSUE THREAD

**Issue by delitescere** [npryce/adr-tools#31]
The output of `adr-config` could be more useful if the absolute path to the directory is known, especially when using its output from a different directory to the one `adr-config` was executing in.

However, it's not necessary or even desirable to use the physical structure (resolved symlinks). The following incantation will, on MacOS and various Linuxes (including BusyBox), emit the full path to the script's directory.

`$(cd -L $(dirname $0) >/dev/null 2>&1 && pwd -L)`

This would emit something like `/home/nat/code/adr-tools/src` rather than just `.` or `../adr-tools/src`.

While not absolutely vital for the `adr-config` provided as a default for when executing from the source distribution, it is a good practice and might help binary package maintainers.

The consequence is if the output is used in anything that would traverse hosts, the absolute file path would probably be invalid (but that is the case for most `..` paths anyway).

**Comment by npryce** [comment]
Good idea.  Will do.

Package maintainers are meant to write their own adr-config to reflect where they place files in their distro.
