### ISSUE TITLE
Load template from a custom path

### ISSUE THREAD

**Issue by rodrigorznd** [npryce/adr-tools#33]
Would be nice, for reasons of language for example

**Comment by stephengazzard** [comment]
I'd like to see this as well - especially if this could be specified in a config file at my project root (`.adr.yml` or something along those lines, which may supercede the `.adr-dir` file that currently exists). Specifically I'd like to keep the existing format, but add another row.

**Comment by NoOrdInaryGuy** [comment]
:+1: It would be nice to do this without needing a custom build.

**Comment by npryce** [comment]
The tool looks for a template in the ADR directory, before falling back to the default.

**Comment by npryce** [comment]
I'll improve the help text.
