### ISSUE TITLE
Improve documentation on TOC and Generate options

### ISSUE THREAD

**Issue by jlo-photobox** [npryce/adr-tools#36]
I've been assessing the tool (great work!) and found that it took me a while to discover the format of the generate graph option. I had to run `adr help generate graph` in order to find it, but took me a while to realise that there was help for generate graph and generate toc independently.

Maybe split the actions into adr graph and adr toc?

**Comment by npryce** [comment]
I'm thinking I'll rename them to `adr generate-graph` and `adr generate-toc`.  That is, have only one level of subcommand.

**Comment by jmeijrink** [comment]
It could also just be mentioned in _adr help generate_ output that help for the specific commands can be requested as well.

**Comment by npryce** [comment]
I've improved the help text for `adr generate` to describe how to get help on using the generate subcommands.
