### ISSUE TITLE
This repos ADRs do not themselves use ISO date format

### ISSUE THREAD

**Issue by binkley** [npryce/adr-tools#37]
While browsing the ADR for ISO date format, I noticed the card itself wasn't using that format:

https://github.com/npryce/adr-tools/blob/master/doc/adr/0008-use-iso-8601-format-for-dates.md

```
# 8. Use ISO 8601 Format for Dates

Date: 21/02/2017
```

Have you run `upgrade-repository` on this repo?

**Comment by npryce** [comment]
Good catch.  I have not.

**Comment by npryce** [comment]
I have now.
