### ISSUE TITLE
doc/adr vs. docs/adr

### ISSUE THREAD

**Issue by koppor** [npryce/adr-tools#39]
[GitHub pages](https://pages.github.com/) allows for publishing websites on github. As source, they have following sources

- `gh-pages` branch, folder `/`
- `master` branch, folder `/`
- `master` branch, folder `/docs`. - https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch

Note the `s` in the folder name. 

In the (unrelated) project Eclipse Winery, [the homepage](http://eclipse.github.io/winery/) is rendered from `docs/`. The ADRs are placed into the folder `docs/adr`. As a consequence, the ADRs are browsable in the homepage: http://eclipse.github.io/winery/adr/

In case the ADRs resided in `doc/adr`, there would be two folders, `docs/` for the whole homepage and `doc/adr` for all the ADRs.

Therefore, I propose to rename the folder `doc` to `docs`. I would submit a pull request, but seeing a nice test coverage (refs https://github.com/npryce/adr-tools/pull/30#issuecomment-343249661), I would only start if this is a consensus to rename the directory.

**Comment by retnuh** [comment]
You can use whatever directory you like, when you call `adr init` command.  I think that perhaps the README could be a bit clearer and more consistent about this, however.

**Comment by koppor** [comment]
I  would, however, change the **default** path to `docs/adr`.

This hits this repo itself: https://github.com/npryce/adr-tools/tree/master/doc/adr would be renamed to docs/adr.

Additionally, the README and code:

- https://github.com/npryce/adr-tools/blob/master/src/_adr_dir#L9
- https://github.com/npryce/adr-tools/blob/master/src/adr-init#L13

**Comment by npryce** [comment]
This would be a backwards incompatible change.  Every current user would have to configure their project to point at their existing directory.

**Comment by koppor** [comment]
@npryce I read that answer that there will be no 3.0.0 version supporting this directly.

I will try to propose a patch checking the default directory for `doc/adr` and if that does not exist, that it checks for `docs/adr`.
