### ISSUE TITLE
Add decisions dir to TOC paths

### ISSUE THREAD

**Issue by gaggle** [npryce/adr-tools#44]
I'd like to output the TOC to an MD file on root of project, but links to the MD files are made so that file would have to be in the decisions dir itself.

I.e.

    * [1. Record architecture decisions](0001-record-architecture-decisions.md)

I'd like a flag in `generate toc` to generate links with the decisions dir added, or perhaps relative to the current folder, or as a string to prefix every path. Which (if any) do you prefer?

I.e.

    * [1. Record architecture decisions](decisions/0001-record-architecture-decisions.md)

(and thanks for making the tool, it's fun and useful :)

**Comment by npryce** [comment]
Great idea!

**Comment by jmeijrink** [comment]
Same for graph generation. Now the toc and graph should probably be placed in the decisions folder. IT would already be helpful to have some guidance on this point, how it was meant to be used.

**Comment by npryce** [comment]
The `generate` subcommands are meant to be used as part of a document publishing pipeline.

I usually have a Makefile that gathers into a temp directory ADR markdown files from the adr directory, the generated table of contents, figures generated from textual diagram formats in the adr directory (PlantUML, mermaid, dot, etc.), and so on; uses Pandoc to generate HTML and PDF; and then publishes to the team web site.
