### ISSUE TITLE
Provide an AppImage

### ISSUE THREAD

**Issue by cartolari** [npryce/adr-tools#47]
It'd be great if the app could be downloaded as a single binary, like the ones provided by an [AppImage](https://github.com/AppImage/AppImageKit).

**Comment by npryce** [comment]
I don't have the time nor knowledge to package the app for evert platform and packaging system, so I leave packaging to downstream projects (for example https://github.com/Homebrew/homebrew-core/blob/master/Formula/adr-tools.rb).  Sorry.  But if you (or someone else) does package adr-tools for AppImage then I'd gladly add that fact to the README and link to it.
