### ISSUE TITLE
TOGAF 9.1 Architectural Principle format?

### ISSUE THREAD

**Issue by jeevemula** [npryce/adr-tools#50]

**Comment by npryce** [comment]
Can you provide more information?

My understanding is that in TOGAF, Architecture Principles record an architecture's current state, not a history of decisions.  So ADRs are a superset of the TOGAF format, with links between decisions.  The current state can be determined by removing obsolete decisions from the history, as while publishing the documents for example.

As for the TOGAF format,  as long as you keep the "Status" section (which the tool uses to maintain links between ADRs), the rest of the format is flexible.  You can create your own template file with the headings you want to use for your project.

**Comment by npryce** [comment]
Closed until more information is given.
