### ISSUE TITLE
Feature request: search parent directories for `.adr-dir`

### ISSUE THREAD

**Issue by meshy** [npryce/adr-tools#62]
In my company, ADRs live in `architecture/`.

I was in the `architecture/` dir, and ran `adr new ...`, and was surprised to find that a `architecture/doc/adr` folder was created.

It'd be great if `_adr_dir` searched in parent directories to see if there was a `.adr-dir`, just as `git` searches parent directories for a `.git`.

Thanks for this great project, by the way! :)

**Comment by npryce** [comment]
I want this and should have implemented it this way from the start. I’ll have to think about how it would interact with the behaviour described in issues #48.

**Comment by npryce** [comment]
I think that this is such a significant usability improvement that it should be released first, and then #48 implemented in a way that works with the search mechanism. I have an implementation that I will push this evening.

**Comment by npryce** [comment]
Implemented in 3.0.0

**Comment by meshy** [comment]
Thank you very much!
