### ISSUE TITLE
adr-tools doesn't work correctly in git bash because `more` is missing

### ISSUE THREAD

**Issue by andrew-schofield** [npryce/adr-tools#68]
The linux toolset included with git bash is missing `more` which means that adr help (f.e.) doesn't work.
git bash does have `less` which works just as well, so my initial workaround was to copy less.exe to more.exe in the git bash usr/bin/ folder.

Is there a technical reason why adr-tools uses `more` rather than `less`? Could it be changed without breaking other platforms?

I can submit a PR with an updated INSTALL.md which includes a note about copying less to more, or I can submit a PR with the shell script change to use less instead of more.

**Comment by retnuh** [comment]
Ideally adr should use $PAGER if it’s set; then check for more and/or less
as a fallback.

**Comment by andrew-schofield** [comment]
In that case the install instructions for git bash do need updating, as it neither defines $PAGER nor has the POSIX compliant `more`

**Comment by npryce** [comment]
Yes. See #69 (contributions welcome)
