### ISSUE TITLE
Content licensing?

### ISSUE THREAD

**Issue by aepsil0n** [npryce/adr-tools#85]
I am somewhat confused by this clause in the LICENSE.txt

> Content that this tool adds to your project is under the
> [Creative Commons Attribution 4.0 (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/) licence.

Does this only apply to the automatically generated phrasing of the ADRs? It surely does not apply to the content that you fill in, does it? It may be helpful to clarify this.

**Comment by npryce** [comment]
My thinking was that it applies to the initial ADR, so that if a project publishes its ADRs, it doesn't get embroiled in IP issues.  I don't think that the document structure, section titles, etc. in the ADR templates are something that can be copyrighted or need licensing.

**Comment by PeterMTaylor** [comment]
Although not part of ADR however food for thought regarding content license https://meta.stackexchange.com/questions/333089/stack-exchange-and-stack-overflow-are-moving-to-cc-by-sa-4-0
